ProyectoFinalPredictiva.ipynb
Automatically generated by Colab.
Original file is located at https://colab.research.google.com/drive/1xENeViTGXWezyjcbiSjgETvzjd8fd9vB

## Predicción Discreta (Clasificación): Arbol de Decisión, Red Neuronal, KNN.
Proyecto Final de Minería de Datos -
Realizado por Blanca Janeth Yepes

### 1. Carga y Decodificación de Datos ARFF
#Importar librerías
import pandas as pd
from scipy.io import arff
import numpy as np

### 4. Creación y Evaluación de Modelos Individuales
Entrenamiento evaluación individual de los tres modelos de clasificación: el Árbol de Decisión, la Red Neuronal (MLP) y el algoritmo K-Nearest Neighbors (KNN).

#### A. Árbol de Decisión (Entrenamiento sin normalización)

from sklearn.tree import DecisionTreeClassifier, plot_tree
from sklearn import metrics
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np # Importar numpy

print("\n--- ENTRENANDO Y EVALUANDO ÁRBOL DE DECISIÓN ---")

# Aprendizaje
# Se usan datos balanceados (X_train_bal), NO normalizados (X_train_bal proviene de X_train_bal.copy() antes de normalizar)
# Se reduce max_depth para acelerar el entrenamiento del ensamble.
model_dt = DecisionTreeClassifier(criterion='gini', min_samples_leaf=2, max_depth=7, random_state=42) # Reducido de 10 a 7
model_dt.fit(X_train_bal, Y_train_bal)

# Predicción y Reporte
Y_pred_dt = model_dt.predict(X_test) # X_test no está normalizado para el árbol
print("\nReporte de Clasificación del Árbol de Decisión:")
print(metrics.classification_report(Y_test, Y_pred_dt, target_names=labelencoder.classes_))

# Visual: Gráfica del Árbol (puede ser muy grande para datasets complejos)
plt.figure(figsize=(25,15))
plot_tree(model_dt, feature_names=X.columns.tolist(), class_names=labelencoder.classes_, rounded=True, filled=True, fontsize=8)
plt.title("Árbol de Decisión")
plt.show()

# Visual: Matriz de Confusión
print("\nMatriz de Confusión del Árbol de Decisión:")
disp = metrics.ConfusionMatrixDisplay(confusion_matrix=metrics.confusion_matrix(Y_test, Y_pred_dt), display_labels=labelencoder.classes_)
disp.plot(cmap=plt.cm.Blues)
plt.title("Matriz de Confusión - Árbol de Decisión")
plt.show()

# Visual: Curva ROC para multiclase (One-vs-Rest)
print("\nCurva ROC del Árbol de Decisión (One-vs-Rest) para cada clase:")

y_score_dt = model_dt.predict_proba(X_test)

plt.figure(figsize=(10, 8))
for i, class_name in enumerate(labelencoder.classes_):
    # Binarizar Y_test para la clase actual (One-vs-Rest)
    y_test_bin = (Y_test == i).astype(int)

    # Calcular FPR, TPR y umbrales
    fpr, tpr, _ = metrics.roc_curve(y_test_bin, y_score_dt[:, i])

    # Graficar la curva ROC
    plt.plot(fpr, tpr, label=f'ROC de {class_name} (AUC = {metrics.auc(fpr, tpr):.2f})')

plt.plot([0, 1], [0, 1], 'k--', label='Clasificador aleatorio') # Línea de base
plt.xlabel('Tasa de Falsos Positivos (FPR)')
plt.ylabel('Tasa de Verdaderos Positivos (TPR)')
plt.title('Curva ROC - Árbol de Decisión (Multiclase One-vs-Rest)')
plt.legend(loc='lower right')
plt.grid(True)
plt.show()

#### B. Red Neuronal - MLP (Entrenamiento con datos normalizados)

from sklearn.neural_network import MLPClassifier
from sklearn import metrics # Importar metrics
import matplotlib.pyplot as plt # Importar plt
import numpy as np # Importar numpy

print("\n--- ENTRENANDO Y EVALUANDO RED NEURONAL (MLP) ---")

# Aprendizaje:
# Se usan datos balanceados Y normalizados (X_train_norm)
# Se reduce max_iter para acelerar el entrenamiento del ensamble.
model_rn = MLPClassifier(activation="logistic", hidden_layer_sizes=(50,),
                         learning_rate='constant', learning_rate_init=0.02,
                         momentum=0.03, max_iter=100, random_state=3, verbose=False) # Reducido de 500 a 100
model_rn.fit(X_train_norm, Y_train_bal)

# Visual: Curva de Pérdida (Chequeo de sobreentrenamiento)
print("\nCurva de Pérdida de la Red Neuronal:")
plt.figure(figsize=(10, 6))
plt.plot(model_rn.loss_curve_)
plt.title("Curva de Pérdida - Red Neuronal")
plt.xlabel("Épocas")
plt.ylabel("Pérdida")
plt.grid(True)
plt.show()

# Predicción y Reporte
Y_pred_rn = model_rn.predict(X_test_norm) # X_test normalizado para la RN
print("\nReporte de Clasificación de la Red Neuronal:")
print(metrics.classification_report(Y_test, Y_pred_rn, target_names=labelencoder.classes_))

# Visual: Matriz de Confusión
print("\nMatriz de Confusión de la Red Neuronal:")
disp = metrics.ConfusionMatrixDisplay(confusion_matrix=metrics.confusion_matrix(Y_test, Y_pred_rn), display_labels=labelencoder.classes_)
disp.plot(cmap=plt.cm.Greens)
plt.title("Matriz de Confusión - Red Neuronal")
plt.show()

# Visual: Curva ROC para multiclase (One-vs-Rest)
print("\nCurva ROC de la Red Neuronal (One-vs-Rest) para cada clase:")

y_score_rn = model_rn.predict_proba(X_test_norm)

plt.figure(figsize=(10, 8))
for i, class_name in enumerate(labelencoder.classes_):
    # Binarizar Y_test para la clase actual (One-vs-Rest)
    y_test_bin = (Y_test == i).astype(int)

    # Calcular FPR, TPR y umbrales
    fpr, tpr, _ = metrics.roc_curve(y_test_bin, y_score_rn[:, i])

    # Graficar la curva ROC
    plt.plot(fpr, tpr, label=f'ROC de {class_name} (AUC = {metrics.auc(fpr, tpr):.2f})')

plt.plot([0, 1], [0, 1], 'k--', label='Clasificador aleatorio') # Línea de base
plt.xlabel('Tasa de Falsos Positivos (FPR)')
plt.ylabel('Tasa de Verdaderos Positivos (TPR)')
plt.title('Curva ROC - Red Neuronal (Multiclase One-vs-Rest)')
plt.legend(loc='lower right')
plt.grid(True)
plt.show()

#### C. K-Nearest Neighbors - KNN (Entrenamiento con datos normalizados)

from sklearn.neighbors import KNeighborsClassifier
from sklearn import metrics
import matplotlib.pyplot as plt
import numpy as np

print("\n--- ENTRENANDO Y EVALUANDO K-NEAREST NEIGHBORS (KNN) ---")

# Aprendizaje
# Se usan datos balanceados Y normalizados (X_train_norm)
model_knn = KNeighborsClassifier(n_neighbors=5, metric='euclidean') # Se pueden ajustar n_neighbors
model_knn.fit(X_train_norm, Y_train_bal)

# Predicción y Reporte
Y_pred_knn = model_knn.predict(X_test_norm) # X_test normalizado para KNN
print("\nReporte de Clasificación de KNN:")
print(metrics.classification_report(Y_test, Y_pred_knn, target_names=labelencoder.classes_))

# Visual: Matriz de Confusión
print("\nMatriz de Confusión de KNN:")
disp = metrics.ConfusionMatrixDisplay(confusion_matrix=metrics.confusion_matrix(Y_test, Y_pred_knn), display_labels=labelencoder.classes_)
disp.plot(cmap=plt.cm.Reds)
plt.title("Matriz de Confusión - KNN")
plt.show()

# Visual: Curva ROC para multiclase (One-vs-Rest)
print("\nCurva ROC de KNN (One-vs-Rest) para cada clase:")

y_score_knn = model_knn.predict_proba(X_test_norm)

plt.figure(figsize=(10, 8))
for i, class_name in enumerate(labelencoder.classes_):
    # Binarizar Y_test para la clase actual (One-vs-Rest)
    y_test_bin = (Y_test == i).astype(int)

    # Calcular FPR, TPR y umbrales
    fpr, tpr, _ = metrics.roc_curve(y_test_bin, y_score_knn[:, i])

    # Graficar la curva ROC
    plt.plot(fpr, tpr, label=f'ROC de {class_name} (AUC = {metrics.auc(fpr, tpr):.2f})')

plt.plot([0, 1], [0, 1], 'k--', label='Clasificador aleatorio') # Línea de base
plt.xlabel('Tasa de Falsos Positivos (FPR)')
plt.ylabel('Tasa de Verdaderos Positivos (TPR)')
plt.title('Curva ROC - KNN (Multiclase One-vs-Rest)')
plt.legend(loc='lower right')
plt.grid(True)
plt.show()

# 1. Definir el nombre del archivo a subir a GitHub
filename = 'modelo_knn.pkl'

# 2. Extraer los nombres de las variables predictoras originales (X)
variables_entrenamiento = X.columns.values

# 3. Exportar el Modelo y todas sus herramientas de transformación
with open(filename, 'wb') as archivo:
    pickle.dump([model_knn, variables_entrenamiento, labelencoder, min_max_scaler], archivo)
